import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdThemeProvider } from "EmoEase/components/Themes/AntdThemeProvider";
import { ThemeProvider } from "EmoEase/Provider/ThemeProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ChartThemeProvider } from "EmoEase/Provider/ChartThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EmoEase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <AntdRegistry />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <AntdThemeProvider>
            <ChartThemeProvider>
              {children}
            </ChartThemeProvider>
          </AntdThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
