import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdThemeProvider } from "EmoEase/components/Themes/AntdThemeProvider";
import { ThemeProvider } from "EmoEase/Provider/ThemeProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ChartThemeProvider } from "EmoEase/Provider/ChartThemeProvider";
import { NotificationProvider } from "EmoEase/Provider/NotificationProvider";
import '@ant-design/v5-patch-for-react-19';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL('https://emoease-frontend.vercel.app'),
  title: { default: 'EmoEase', template: '%s | EmoEase' },
  description: 'Generated by create next app',
  openGraph: {
    type: 'website',
    locale: 'vi_VN',
    url: '/',
    title: 'EmoEase',
    description: 'EmosEase – Nơi chăm sóc tinh thần của bạn',
    siteName: 'EmoEase',
    images: [
      {
        url: 'https://emoease-frontend.vercel.app/emo.png',
        width: 1200,
        height: 630,
        alt: 'EmoEase logo',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'EmoEase',
    description: 'Generated by create next app',
    images: ['https://emoease-frontend.vercel.app/emo.png'],
  },
  icons: {
    icon: [
      {
        media: '(prefers-color-scheme: light)',
        url: '/emo.png',
        href: '/emo.png',
      },
      {
        media: '(prefers-color-scheme: dark)',
        url: '/emo.png',
        href: '/emo.png',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <ThemeProvider>
            <AntdThemeProvider>
              <ChartThemeProvider>
                <NotificationProvider>{children}</NotificationProvider>
              </ChartThemeProvider>
            </AntdThemeProvider>
          </ThemeProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
